In [11]:
import numpy as np
import pandas as pd

In [13]:
df=pd.read_csv("userbehaviour.csv")

In [15]:
print("before encoding:")
df.head(5)

before encoding:

,userid,Average Screen Time,Average Spent on App (INR),Left Review,Ratings,New Password Request,Last Visited Minutes,Status
0,1001,17.0,634.0,1,9,7,2990,Installed
1,1002,0.0,54.0,0,4,8,24008,Uninstalled
2,1003,37.0,207.0,0,8,5,971,Installed
3,1004,32.0,445.0,1,6,2,799,Installed
4,1005,45.0,427.0,1,5,6,3668,Installed

In [21]:
df=df.dropna()

In [23]:
from sklearn.preprocessing import LabelEncoder

In [27]:
# Create LabelEncoder objects
status_encoder=LabelEncoder()


#Apply label encoding
df["Status"]=status_encoder.fit_transform(df["Status"])

print("after label encoding:")
print(df)

after label encoding:
     userid  Average Screen Time  Average Spent on App (INR)  Left Review  \
0      1001                 17.0                       634.0            1
1      1002                  0.0                        54.0            0
2      1003                 37.0                       207.0            0
3      1004                 32.0                       445.0            1
4      1005                 45.0                       427.0            1
..      ...                  ...                         ...          ...
994    1995                 38.0                       938.0            0
995    1996                 43.0                        61.0            0
996    1997                 47.0                       761.0            0
997    1998                  6.0                        73.0            1
998    1999                  9.0                        54.0            0

     Ratings  New Password Request  Last Visited Minutes  Status
0          9                     7                  2990       0
1          4                     8                 24008       1
2          8                     5                   971       0
3          6                     2                   799       0
4          5                     6                  3668       0
..       ...                   ...                   ...     ...
994        5                     4                  1865       0
995        6                     8                  1327       0
996        6                     1                  1936       0
997        5                     1                  3436       0
998        4                     2                  4039       0

[999 rows x 8 columns]

In [35]:
# Standardization

from sklearn.preprocessing import StandardScaler
scaler_standard = StandardScaler()
df_standardized = df.copy()
df_standardized[df.columns] = scaler_standard.fit_transform(df)

df_standardized.to_csv("userbehaviour_standardized.csv", index=False)
print("after standardization:")
print(df_standardized)

after standardization:
       userid  Average Screen Time  Average Spent on App (INR)  Left Review  \
0   -1.730318            -0.519415                    0.671295     1.005018
1   -1.726850            -1.714218                   -1.186433    -0.995007
2   -1.723383             0.886235                   -0.696377    -0.995007
3   -1.719915             0.534823                    0.065932     1.005018
4   -1.716448             1.448495                    0.008278     1.005018
..        ...                  ...                         ...          ...
994  1.716448             0.956518                    1.645001    -0.995007
995  1.719915             1.307930                   -1.164012    -0.995007
996  1.723383             1.589060                    1.078073    -0.995007
997  1.726850            -1.292523                   -1.125576     1.005018
998  1.730318            -1.081675                   -1.186433    -0.995007

      Ratings  New Password Request  Last Visited Minutes    Status
0    0.920867              0.739449             -0.246968 -0.301017
1   -0.930876              1.098744              2.200476  3.322069
2    0.550518              0.020860             -0.482071 -0.301017
3   -0.190179             -1.057024             -0.502100 -0.301017
4   -0.560528              0.380154             -0.168019 -0.301017
..        ...                   ...                   ...       ...
994 -0.560528             -0.338435             -0.377969 -0.301017
995 -0.190179              1.098744             -0.440617 -0.301017
996 -0.190179             -1.416318             -0.369702 -0.301017
997 -0.560528             -1.416318             -0.195034 -0.301017
998 -0.930876             -1.057024             -0.124817 -0.301017

[999 rows x 8 columns]

In [43]:
# Normalization
from sklearn.preprocessing import MinMaxScaler
scaler_minmax = MinMaxScaler()
df_normalized = df.copy()
df_normalized[df.columns] = scaler_minmax.fit_transform(df)


df_normalized.to_csv("userbehaviour_normalized.csv")

print("after normalization:")
print(df_normalized)

after normalization:
       userid  Average Screen Time  Average Spent on App (INR)  Left Review  \
0    0.000000                 0.34                    0.635271          1.0
1    0.001002                 0.00                    0.054108          0.0
2    0.002004                 0.74                    0.207415          0.0
3    0.003006                 0.64                    0.445892          1.0
4    0.004008                 0.90                    0.427856          1.0
..        ...                  ...                         ...          ...
994  0.995992                 0.76                    0.939880          0.0
995  0.996994                 0.86                    0.061122          0.0
996  0.997996                 0.94                    0.762525          0.0
997  0.998998                 0.12                    0.073146          1.0
998  1.000000                 0.18                    0.054108          0.0

     Ratings  New Password Request  Last Visited Minutes  Status
0        0.9              0.428571              0.056328     0.0
1        0.4              0.500000              0.480814     1.0
2        0.8              0.285714              0.015551     0.0
3        0.6              0.071429              0.012077     0.0
4        0.5              0.357143              0.070021     0.0
..       ...                   ...                   ...     ...
994      0.5              0.214286              0.033607     0.0
995      0.6              0.500000              0.022741     0.0
996      0.6              0.000000              0.035041     0.0
997      0.5              0.000000              0.065335     0.0
998      0.4              0.071429              0.077513     0.0

[999 rows x 8 columns]

In [45]:
#Ordinal Encoding
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv("userbehaviour.csv")

df = df.dropna()

ordinal_encoder = OrdinalEncoder()
df["Status"] = ordinal_encoder.fit_transform(df[["Status"]])

df.to_csv("userbehaviour_ordinal.csv")

print("after ordinal encoding:")
print(df.head())

after ordinal encoding:
   userid  Average Screen Time  Average Spent on App (INR)  Left Review  \
0    1001                 17.0                       634.0            1
1    1002                  0.0                        54.0            0
2    1003                 37.0                       207.0            0
3    1004                 32.0                       445.0            1
4    1005                 45.0                       427.0            1

   Ratings  New Password Request  Last Visited Minutes  Status
0        9                     7                  2990     0.0
1        4                     8                 24008     1.0
2        8                     5                   971     0.0
3        6                     2                   799     0.0
4        5                     6                  3668     0.0

In [47]:
#One hot encoding
import numpy as np
import pandas as pd

dfhot=pd.read_csv("userbehaviour.csv")

print("before encoding:")
print(dfhot.head(5))

before encoding:
   userid  Average Screen Time  Average Spent on App (INR)  Left Review  \
0    1001                 17.0                       634.0            1
1    1002                  0.0                        54.0            0
2    1003                 37.0                       207.0            0
3    1004                 32.0                       445.0            1
4    1005                 45.0                       427.0            1

   Ratings  New Password Request  Last Visited Minutes       Status
0        9                     7                  2990    Installed
1        4                     8                 24008  Uninstalled
2        8                     5                   971    Installed
3        6                     2                   799    Installed
4        5                     6                  3668    Installed

In [49]:
from sklearn.preprocessing import OneHotEncoder

In [51]:
ohe=OneHotEncoder(drop="first",sparse_output=False,dtype=np.int32)

In [53]:
ohe.fit_transform(dfhot[["Average Screen Time","Average Spent on App (INR)","Left Review","Ratings","New Password Request","Last Visited Minutes","Status"]])

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [55]:
#get_dummies
df=pd.read_csv("userbehaviour.csv")
df.head(2)

,userid,Average Screen Time,Average Spent on App (INR),Left Review,Ratings,New Password Request,Last Visited Minutes,Status
0,1001,17.0,634.0,1,9,7,2990,Installed
1,1002,0.0,54.0,0,4,8,24008,Uninstalled

In [57]:
df=df.dropna()

In [65]:
gd=pd.get_dummies(df, columns=["Status"])

In [67]:
gd=gd.astype(int)

In [69]:
gd

,userid,Average Screen Time,Average Spent on App (INR),Left Review,Ratings,New Password Request,Last Visited Minutes,Status_Installed,Status_Uninstalled
0,1001,17,634,1,9,7,2990,1,0
1,1002,0,54,0,4,8,24008,0,1
2,1003,37,207,0,8,5,971,1,0
3,1004,32,445,1,6,2,799,1,0
4,1005,45,427,1,5,6,3668,1,0
...,...,...,...,...,...,...,...,...,...
994,1995,38,938,0,5,4,1865,1,0
995,1996,43,61,0,6,8,1327,1,0
996,1997,47,761,0,6,1,1936,1,0
997,1998,6,73,1,5,1,3436,1,0
998,1999,9,54,0,4,2,4039,1,0